### ISSUE TITLE
为什么把问题当作二分类问题？

### ISSUE THREAD

**Issue by MLjian** [beader/ruijin_round2#3]
我觉得可以这样，对抽取出来的实体做组合，然后对每个实体对直接做多分类不就可以了么

**Comment by beader** [comment]
因为复赛中，entity 在 train 和 test 中都已经给定了，不需要做 NER，只需要做 Relation 抽取。另外并不是所有的实体对(entity pair)都能形成relation的，比如只有 Test_Disease，没有 Method_Disease。因此在抽取 entity pair 的时候，首先做两两组合，然后过滤掉不存在于题目要求的那10种 relation 的 entity pairs。抽取出的 relation 的类型，由两边 entity type 就决定了，因此只需要判断 entity pair 能否形成 relation，而不需要判断 relation type。

**Comment by MLjian** [comment]
我大概理解了。也就是，其实所有的关系是预先设定好的，所以在抽出实体对后，可以先剔除那些不符合关系要求的。然后又会存在一种情况，比如，“阿莫奇林是一种很重要的药，通常阿莫奇林一次服用一片。”，第一个"阿莫奇林"和“一片”的lable就应该是0， 第二个为1。是这样的吧。。。。

**Comment by beader** [comment]
是这样
