### ISSUE TITLE
关于模型的一些疑惑点

### ISSUE THREAD

**Issue by eclipse-du** [beader/ruijin_round2#4]
1.抱歉由于看不到数据，不了解数据特性，为什么要把训练窗口设为两句话？是因为指代的问题吗？
2.切句的逻辑是用\n和。来分割的吗？
3.楼主当时试过TEXTCNN之类的方法么？是不是残差的表现更好？
4.有没有考虑过加入除了位置以外其它特征，用于提高效果？

p.s.:楼主首页的神经网络图缺了entity distance这个哦，不过整体写的很棒了，点赞

**Comment by beader** [comment]
1. 这里需要考虑 candidate entity pairs 的数量以及覆盖率的问题。如果句子太长，candidate entity pairs 的数量会很多，会造成二分类的时候 0 和 1 的比例差异很大。如果句子太短，那么很多真实的 relation 不会出现在 candidate entity pairs 中，导致 recall 会很低。把窗口定为两句话，大概能覆盖真实 85% 左右的 relation，定为三句话，覆盖率并没有显著提升。
2. 切句子是用中文句号`。`，因为原始数据是从其他格式的文档中提取的，因此会发现大量单词中间存在 `\n` 的例子，因此我认为用 `\n` 切分句子可能不太合理。
3. 没有尝试过 textcnn。加残差的效果确实有更好。
4. 因为复赛每天只有一次机会，我一开始没有什么思路，比较晚才产出一个还不错的 baseline，所以并没有尝试其他更多的特征了。
5. 感谢提醒，图片中忘了加 entity distance 这个特征，他是在 `Dense(256)` 层之前和被 `Concat` 进去的。
